service: workshop-aws-python

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  profile: flo
  environment:
    TEST_ENV: ${file(env.yml):${opt:stage, self:provider.stage}.TEST_ENV}
    FILE_LIST_TABLE: ${file(env.yml):${opt:stage, self:provider.stage}.FILE_LIST_TABLE}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:*:*:table/${file(env.yml):${opt:stage, self:provider.stage}.FILE_LIST_TABLE}

functions:
  hello:
    handler: handler.hello
    timeout: 30
    events:
      - http:
          path: api/hello
          method: get
          integration: lambda
          cors: true
  createItem:
    handler: api/dynamoDB/handler.createItem
    timeout: 30
    events:
      - http:
          path: api/dynamoDB/createItem
          method: post
          integration: lambda
          cors: true
  getItems:
    handler: api/dynamoDB/handler.getItems
    timeout: 30
    events:
      - http:
          path: api/dynamoDB/getItems
          method: get
          integration: lambda
          cors: true

resources:
  Resources:
    FileList:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(env.yml):${opt:stage, self:provider.stage}.FILE_LIST_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
